# Generated by Django 3.2.7 on 2021-09-05 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import issues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='název')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='název')),
                ('mark_issue_as_finished', models.BooleanField(default=False, verbose_name='označit issue jako dokončené')),
            ],
            options={
                'verbose_name': 'Stav',
                'verbose_name_plural': 'Stavy',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='název')),
                ('description', models.TextField(verbose_name='popis')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 9, 5, 21, 32, 43, 996545), verbose_name='vytvořeno')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='dokončeno')),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.category', verbose_name='kategorie')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, validators=[issues.models.validate_superuser], verbose_name='zadavatel')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_person', to=settings.AUTH_USER_MODEL, verbose_name='řešitel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.state', verbose_name='stav')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ('-created_at', 'name', 'state'),
            },
        ),
    ]
